from settings import *

current_config = {
    "VERSION": versionNumber,
    "SERVER_URL": SERVER_URL,
    "OPT_IMAGE_URL": OPT_IMAGE_URL,
    "TIMEZONE": TIMEZONE,
    "PLAYBACK_ROLE": PLAYBACK_ROLE,
    "OWNER_ONLY": OWNER_ONLY,
    "TASK_FREQUENCY": TASK_FREQUENCY,
    "AUDIO_ENABLED": AUDIO_ENABLED,
    "MULTI_USER": MULTI_USER
}


